spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/liner?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: liner
    password: 1234
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/liner?characterEncoding=UTF-8&serverTimezone=UTC
      username: liner
      password: 1234
      connection-test-query: SELECT NOW() FROM dual

mybatis:
  type-aliases-package: com.example.linertest.domain
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8000

---

spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8888

---

spring:
  config:
    activate:
      on-profile: prod
server:
  port: 80